import type { VariablesType } from "@/types/anilist/variables.type";

export const ParameterType = {
  "Int"            : "Int",
  "String"         : "String",
  "Boolean"        : "Boolean",
  "ArrayOfString"  : "[String]",
  "MediaSeason"    : "MediaSeason",
  "MediaType"      : "MediaType",
  "MediaFormat"    : "MediaFormat",
  "MediaStatus"    : "MediaStatus",
  "MediaListStatus": "MediaListStatus",
  "MediaSource"    : "MediaSource",
  "MediaSort"      : "[MediaSort]",
  "FuzzyDateInt"   : "FuzzyDateInt",
};
export const QueryParametersType: Record<keyof VariablesType, string> = {
  "id"                  : ParameterType.Int,
  "idMal"               : ParameterType.Int,
  "season"              : ParameterType.MediaSeason,
  "seasonYear"          : ParameterType.Int,
  "type"                : ParameterType.MediaType,
  "format"              : ParameterType.MediaFormat,
  "status"              : ParameterType.MediaStatus,
  "episodes"            : ParameterType.Int,
  "duration"            : ParameterType.Int,
  "isAdult"             : ParameterType.Boolean,
  "genre"               : ParameterType.String,
  "genre_in"            : ParameterType.ArrayOfString,
  "tag_in"              : ParameterType.ArrayOfString,
  "tag"                 : ParameterType.String,
  "onList"              : ParameterType.Boolean,
  "licensedBy"          : ParameterType.String,
  "licensedById"        : ParameterType.Int,
  "averageScore"        : ParameterType.Int,
  "averageScore_greater": ParameterType.Int,
  "popularity"          : ParameterType.Int,
  "search"              : ParameterType.String,
  "sort"                : ParameterType.MediaSort,
  "source"              : ParameterType.MediaSource,
  "userName"            : ParameterType.String,
  "mediaListStatus"     : ParameterType.MediaListStatus,
  "startDate_greater"   : ParameterType.FuzzyDateInt,
  "endDate_lesser"      : ParameterType.FuzzyDateInt,
  "episodes_greater"    : ParameterType.Int,
  "episodes_lesser"     : ParameterType.Int,
  "duration_greater"    : ParameterType.Int,
  "duration_lesser"     : ParameterType.Int,
};
